# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindows.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1098, 794)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEditSendAera = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditSendAera.setMinimumSize(QtCore.QSize(0, 100))
        self.lineEditSendAera.setMaximumSize(QtCore.QSize(16777215, 100))
        self.lineEditSendAera.setObjectName("lineEditSendAera")
        self.gridLayout_3.addWidget(self.lineEditSendAera, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textEditRevAera = QtWidgets.QTextEdit(self.tab)
        self.textEditRevAera.setEnabled(True)
        self.textEditRevAera.setMouseTracking(False)
        self.textEditRevAera.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textEditRevAera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEditRevAera.setObjectName("textEditRevAera")
        self.gridLayout_4.addWidget(self.textEditRevAera, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1098, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_savelog = QtWidgets.QAction(MainWindow)
        self.action_savelog.setObjectName("action_savelog")
        self.action_runscript = QtWidgets.QAction(MainWindow)
        self.action_runscript.setObjectName("action_runscript")
        self.action_stopscript = QtWidgets.QAction(MainWindow)
        self.action_stopscript.setEnabled(False)
        self.action_stopscript.setObjectName("action_stopscript")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_savelog)
        self.menu_2.addAction(self.action_runscript)
        self.menu_2.addAction(self.action_stopscript)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "发送区域"))
        self.groupBox.setTitle(_translate("MainWindow", "接收区域"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "脚本"))
        self.action.setText(_translate("MainWindow", "连接"))
        self.action_savelog.setText(_translate("MainWindow", "保存日志"))
        self.action_runscript.setText(_translate("MainWindow", "执行"))
        self.action_stopscript.setText(_translate("MainWindow", "取消"))

