# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting_serial.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(430, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_port = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_port.setEditable(True)
        self.comboBox_port.setObjectName("comboBox_port")
        self.gridLayout.addWidget(self.comboBox_port, 0, 2, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 2)
        self.comboBox_baudrate = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_baudrate.setEditable(True)
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.gridLayout.addWidget(self.comboBox_baudrate, 1, 2, 1, 2)
        self.comboBox_databit = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_databit.setObjectName("comboBox_databit")
        self.comboBox_databit.addItem("")
        self.comboBox_databit.addItem("")
        self.comboBox_databit.addItem("")
        self.comboBox_databit.addItem("")
        self.gridLayout.addWidget(self.comboBox_databit, 2, 2, 1, 2)
        self.comboBox_parity = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_parity.setObjectName("comboBox_parity")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.gridLayout.addWidget(self.comboBox_parity, 3, 2, 1, 2)
        self.comboBox_stopbits = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_stopbits.setObjectName("comboBox_stopbits")
        self.comboBox_stopbits.addItem("")
        self.comboBox_stopbits.addItem("")
        self.comboBox_stopbits.addItem("")
        self.gridLayout.addWidget(self.comboBox_stopbits, 4, 2, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 2, 1, 1)
        self.connection_connect_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connection_connect_button.sizePolicy().hasHeightForWidth())
        self.connection_connect_button.setSizePolicy(sizePolicy)
        self.connection_connect_button.setMinimumSize(QtCore.QSize(100, 50))
        self.connection_connect_button.setDefault(True)
        self.connection_connect_button.setObjectName("connection_connect_button")
        self.gridLayout.addWidget(self.connection_connect_button, 6, 1, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 430, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "端口"))
        self.label_4.setText(_translate("MainWindow", "奇偶校验"))
        self.label_3.setText(_translate("MainWindow", "数据位"))
        self.label_2.setText(_translate("MainWindow", "波特率"))
        self.label_5.setText(_translate("MainWindow", "停止位"))
        self.comboBox_baudrate.setItemText(0, _translate("MainWindow", "115200"))
        self.comboBox_baudrate.setItemText(1, _translate("MainWindow", "9600"))
        self.comboBox_baudrate.setItemText(2, _translate("MainWindow", "19200"))
        self.comboBox_databit.setItemText(0, _translate("MainWindow", "8"))
        self.comboBox_databit.setItemText(1, _translate("MainWindow", "5"))
        self.comboBox_databit.setItemText(2, _translate("MainWindow", "6"))
        self.comboBox_databit.setItemText(3, _translate("MainWindow", "7"))
        self.comboBox_parity.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_parity.setItemText(1, _translate("MainWindow", "Odd"))
        self.comboBox_parity.setItemText(2, _translate("MainWindow", "Even"))
        self.comboBox_parity.setItemText(3, _translate("MainWindow", "Mark"))
        self.comboBox_parity.setItemText(4, _translate("MainWindow", "Space"))
        self.comboBox_stopbits.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_stopbits.setItemText(1, _translate("MainWindow", "1.5"))
        self.comboBox_stopbits.setItemText(2, _translate("MainWindow", "2"))
        self.connection_connect_button.setText(_translate("MainWindow", "Connect"))

